#include <conio.h>
#include  <iostream.h>
void main()
{
clrscr();
cout <<"RRRRRRRRRRR       AAAAAA      FFFFFFFFFFFF\n";
cout <<"RRRRRRRRRRRR     AAA  AAA     FFFFFFFFFFFF\n";
cout <<"RRRR    RRR     AAA    AAA    FFFF\n";
cout <<"RRRR    RRR     AAA    AAA    FFFF\n";
cout <<"RRRRRRRRRR      AAAAAAAAAA    FFFFFFFFFFFF\n";
cout <<"RRRRRR          AAA    AAA    FFFFFFFFFFFF\n";
cout <<"RRRR  RRRRR    AAAA    AAAA   FFFF\n";
cout <<"RRRR  RRRRRR  AAAAA    AAAAAA FFFF\n";

getch ();
}

